// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM38CnleEHC6QV0uCgxYl0x2vzmkQbyN4',
    appId: '1:98101450898:web:0a755b5f11241f890aee4b',
    messagingSenderId: '98101450898',
    projectId: 'flutter-chatapp-bbc24',
    authDomain: 'flutter-chatapp-bbc24.firebaseapp.com',
    storageBucket: 'flutter-chatapp-bbc24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9RuDmsM3Fscmzbx-g9IvxOXDn1laljYk',
    appId: '1:98101450898:android:157b20fd0d89c1500aee4b',
    messagingSenderId: '98101450898',
    projectId: 'flutter-chatapp-bbc24',
    storageBucket: 'flutter-chatapp-bbc24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_SDFH_8xv8eaGosGtcDc65T8tIRqlPo',
    appId: '1:98101450898:ios:36dc16f3d79faa7d0aee4b',
    messagingSenderId: '98101450898',
    projectId: 'flutter-chatapp-bbc24',
    storageBucket: 'flutter-chatapp-bbc24.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX_SDFH_8xv8eaGosGtcDc65T8tIRqlPo',
    appId: '1:98101450898:ios:36dc16f3d79faa7d0aee4b',
    messagingSenderId: '98101450898',
    projectId: 'flutter-chatapp-bbc24',
    storageBucket: 'flutter-chatapp-bbc24.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM38CnleEHC6QV0uCgxYl0x2vzmkQbyN4',
    appId: '1:98101450898:web:4a5bf3d94816689d0aee4b',
    messagingSenderId: '98101450898',
    projectId: 'flutter-chatapp-bbc24',
    authDomain: 'flutter-chatapp-bbc24.firebaseapp.com',
    storageBucket: 'flutter-chatapp-bbc24.appspot.com',
  );

}